import type { EquipmentApprovalRecord } from "./types";

export const equipmentApprovalRecords: EquipmentApprovalRecord[] = [
  {
    id: "a1",
    date: "2025-04-01",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "全項目正常、異常なし",
    implementer: "佐藤健一",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [
      {
        segment: "始業",
        points: [
          {
            location: "エコスター",
            items: [
              { name: "定量部", status: "ok", timestamp: "2025/04/01 07:15", inspector: "佐藤健一" },
              {
                name: "タンク部",
                status: "ng",
                cause: "汚れ",
                action: "その他　内部に油汚れを確認、分解洗浄を実施済み",
                timestamp: "2025/04/01 07:08",
                inspector: "佐藤健一",
              },
              { name: "駆動ベルト", status: "ok", timestamp: "2025/04/01 06:52", inspector: "佐藤健一" },
            ],
          },
          {
            location: "ボイル槽",
            items: [
              { name: "温度計・水位", status: "ok", timestamp: "2025/04/01 06:52", inspector: "佐藤健一" },
            ],
          },
        ],
        remarks:
          "エコスター タンク部に油汚れを確認。分解洗浄にて対応済み。次回点検時に再確認予定。その他の点検項目は異常なし。",
      },
      {
        segment: "終業",
        points: [
          {
            location: "エコスター",
            items: [
              { name: "定量部", status: "ok", timestamp: "2025/04/01 17:15", inspector: "佐藤健一" },
              {
                name: "タンク部",
                status: "ng",
                cause: "汚れ",
                action: "その他　内部に油汚れを確認、分解洗浄を実施済み",
                timestamp: "2025/04/01 17:08",
                inspector: "佐藤健一",
              },
              { name: "駆動ベルト", status: "ok", timestamp: "2025/04/01 16:52", inspector: "佐藤健一" },
            ],
          },
          {
            location: "ボイル槽",
            items: [
              { name: "温度計・水位", status: "ok", timestamp: "2025/04/01 16:45", inspector: "佐藤健一" },
            ],
          },
        ],
        remarks: "",
      },
    ],
  },
  {
    id: "a2",
    date: "2025-04-01",
    lineLabel: "【毎週】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "高橋美咲",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a3",
    date: "2025-04-01",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ng",
    remarks: "タンク内部に油汚れを確認、分解洗浄にて対応済み",
    implementer: "渡辺真由",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a4",
    date: "2025-04-01",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "skip",
    remarks: "点検見送り ライン停止中のため",
    implementer: "小林誠司",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a5",
    date: "2025-04-02",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "山本拓海",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a6",
    date: "2025-04-02",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ok",
    remarks: "ベルト摩耗あり、次回交換予定",
    implementer: "吉田浩二",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a7",
    date: "2025-04-02",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "ok",
    remarks: "異常なし",
    implementer: "田村康平",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a8",
    date: "2025-04-03",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "松本奈々",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a9",
    date: "2025-04-03",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ok",
    remarks: "",
    implementer: "佐藤健一",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "a10",
    date: "2025-04-03",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "ok",
    remarks: "パッキン交換済み、動作確認完了",
    implementer: "高橋美咲",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
];
