import type { ScaleInspectionPost, ScaleInspectionScale } from "./types";

export const initialScaleInspectionPosts: ScaleInspectionPost[] = [
  { id: "post-additive", factoryId: "f1", name: "添加物" },
  { id: "post-pudding", factoryId: "f1", name: "プリン" },
  { id: "post-topping", factoryId: "f1", name: "トッピング" },
  { id: "post-ice", factoryId: "f1", name: "アイス" },
  { id: "post-catalana", factoryId: "f1", name: "カタラーナ" },
];

export const initialScaleInspectionScales: ScaleInspectionScale[] = [
  {
    id: "scale1",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン①",
    serialNumber: "ABC-123456",
    weightCapacity: 3,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
    displayFrom: "2025-04-01",
    displayTo: "2028-04-01",
  },
  {
    id: "scale2",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン②",
    serialNumber: "ABC-123457",
    weightCapacity: 3,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: "action_needed",
    displayFrom: "2025-04-01",
    displayTo: "2028-04-01",
  },
  {
    id: "scale3",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン③",
    serialNumber: "ABC-123458",
    weightCapacity: 5,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: "repairing",
    displayFrom: "2025-04-01",
    displayTo: "2028-04-01",
  },
  {
    id: "scale4",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン④",
    serialNumber: "ABC-123459",
    weightCapacity: 10,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
  },
  {
    id: "scale5",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン⑤",
    serialNumber: "ABC-123460",
    weightCapacity: 3,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
  },
  {
    id: "scale6",
    factoryId: "f1",
    postId: "post-pudding",
    label: "プリン⑥",
    serialNumber: "ABC-123461",
    weightCapacity: 3,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
  },
  {
    id: "scale7",
    factoryId: "f1",
    postId: "post-ice",
    label: "アイス①",
    serialNumber: "ABC-423456",
    weightCapacity: 3,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
    displayFrom: "2025-04-01",
    displayTo: "2028-04-01",
  },
  {
    id: "scale8",
    factoryId: "f1",
    postId: "post-ice",
    label: "アイス②",
    serialNumber: "ABC-423457",
    weightCapacity: 30,
    recordOperationCheck: true,
    recordLevelCheck: true,
    recordDirtCheck: true,
    recordDisplayValue: true,
    referenceWeight: 100,
    minDisplayUnit: 0.1,
    repairStatus: null,
    displayFrom: "2025-04-01",
    displayTo: "2028-04-01",
  },
];
