import type { WaterSearchRecord } from "./types";

const NORMAL = { status: "normal" as const };

export const mockRecords: WaterSearchRecord[] = [
  {
    id: "wr1",
    date: "2025-04-01",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.6,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 279.2,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "wr2",
    date: "2025-04-01",
    time: "15:00",
    location: "給湯室",
    taste: NORMAL,
    smell: {
      status: "abnormal",
      cause: "不明",
      action: "水を入れ替えて再度確認したところ異常は見られなかった。継続して様子を見る。",
    },
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.5,
    chlorine: 0.3,
    chlorineReplenished: true,
    uvOperatingHours: 279.2,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "wr3",
    date: "2025-04-02",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.7,
    chlorine: 0.2,
    chlorineReplenished: false,
    uvOperatingHours: 283.7,
    uvLampReplaced: false,
    uvIndicatorLight: "off",
    abnormalDetectionLight: "on",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "wr4",
    date: "2025-04-02",
    time: "15:00",
    location: "点検場所B",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.8,
    chlorine: 0.4,
    chlorineReplenished: false,
    uvOperatingHours: 140.1,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "鈴木一郎",
    confirmer: "佐藤花子",
    approvalStatus: "approved",
  },
  {
    id: "wr5",
    date: "2025-04-03",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.6,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 288.5,
    uvLampReplaced: true,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "approved",
  },
  {
    id: "wr6",
    date: "2025-04-03",
    time: "15:00",
    location: "点検場所B",
    taste: NORMAL,
    smell: NORMAL,
    color: { status: "abnormal", cause: "配管洗浄直後のため", action: "30分後に再検査し正常を確認した。" },
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.9,
    chlorine: 0.4,
    chlorineReplenished: false,
    uvOperatingHours: 148.9,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "鈴木一郎",
    confirmer: "佐藤花子",
    approvalStatus: "rejected",
  },
];
