import type { WaterApprovalRecord } from "./types";

const NORMAL = { status: "normal" as const };

export const waterApprovalRecords: WaterApprovalRecord[] = [
  {
    id: "war1",
    date: "2025-04-01",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.6,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 279.2,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "war2",
    date: "2025-04-01",
    time: "15:00",
    location: "給湯室",
    taste: NORMAL,
    smell: { status: "abnormal", cause: "不明", action: "経過観察" },
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.5,
    chlorine: 0.3,
    chlorineReplenished: true,
    uvOperatingHours: 279.2,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "war3",
    date: "2025-04-02",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.7,
    chlorine: 0.2,
    chlorineReplenished: false,
    uvOperatingHours: 283.7,
    uvLampReplaced: false,
    uvIndicatorLight: "off",
    abnormalDetectionLight: "on",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
  {
    id: "war4",
    date: "2025-04-01",
    time: "09:00",
    location: "製造ライン洗浄水",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.8,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 301.4,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "中村健一",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
  },
];
