import type { WaterConfirmationRecord } from "./types";

const NORMAL = { status: "normal" as const };

export const waterConfirmationRecords: WaterConfirmationRecord[] = [
  {
    id: "wcr1",
    date: "2025-04-01",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.6,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 279.2,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    confirmStatus: "confirmed",
    comments: [
      {
        id: "c1",
        author: "鈴木修",
        timestamp: "2026.08.19 10:39",
        text: "検索条件を確認しました。問題ありません。",
      },
      {
        id: "c2",
        author: "山田花子",
        timestamp: "2026.08.23 15:45",
        text: "データ抽出の期間を再度ご確認ください。",
      },
    ],
  },
  {
    id: "wcr2",
    date: "2025-04-01",
    time: "15:00",
    location: "給湯室",
    taste: NORMAL,
    smell: { status: "abnormal", cause: "排水口の詰まり", action: "排水口を清掃し、消臭剤を設置した" },
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.4,
    chlorine: 0.3,
    chlorineReplenished: false,
    uvOperatingHours: 303.7,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    confirmStatus: "unconfirmed",
  },
  {
    id: "wcr3",
    date: "2025-04-02",
    time: "09:00",
    location: "給湯室",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.3,
    chlorine: 0.2,
    chlorineReplenished: false,
    uvOperatingHours: 327.4,
    uvLampReplaced: false,
    uvIndicatorLight: "off",
    abnormalDetectionLight: "on",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    confirmStatus: "confirmed",
  },
  {
    id: "wcr4",
    date: "2025-04-01",
    time: "09:00",
    location: "製造ライン洗浄水",
    taste: NORMAL,
    smell: NORMAL,
    color: NORMAL,
    turbidity: NORMAL,
    foreignMatter: NORMAL,
    ph: 6.8,
    chlorine: 0.4,
    chlorineReplenished: false,
    uvOperatingHours: 140.1,
    uvLampReplaced: false,
    uvIndicatorLight: "on",
    abnormalDetectionLight: "off",
    implementer: "鈴木一郎",
    confirmer: "佐藤花子",
    confirmStatus: "unconfirmed",
  },
];
