import type { AdditiveApprovalRecord } from "./types";

export const additiveApprovalRecords: AdditiveApprovalRecord[] = [
  {
    id: "a1",
    date: "2025-04-01",
    additiveName: "ソルビン酸",
    type: "入庫",
    previousStock: "5,000ml",
    quantity: "1,000ml",
    currentStock: "4,000ml",
    storageLocation: "小型物置",
    remarks: "月次定期発注による補充入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "a2",
    date: "2025-04-01",
    additiveName: "ソルビン酸",
    type: "出庫",
    previousStock: "4,000ml",
    quantity: "500ml",
    currentStock: "3,500ml",
    storageLocation: "小型物置",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "a3",
    date: "2025-04-02",
    additiveName: "ソルビン酸",
    type: "入庫",
    previousStock: "3,500ml",
    quantity: "2,000ml",
    currentStock: "5,500ml",
    storageLocation: "小型物置",
    remarks: "緊急発注分の追加入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "a4",
    date: "2025-04-03",
    additiveName: "ソルビン酸",
    type: "出庫",
    previousStock: "5,500ml",
    quantity: "1,000ml",
    currentStock: "4,500ml",
    storageLocation: "小型物置",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "a5",
    date: "2025-04-03",
    additiveName: "ソルビン酸",
    type: "出庫",
    previousStock: "4,500ml",
    quantity: "500ml",
    currentStock: "4,000ml",
    storageLocation: "小型物置",
    remarks: "豆腐ライン使用分として出庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
];
