import type { FactoryRecord } from "./types";

export const INITIAL_FACTORY_RECORDS: FactoryRecord[] = [
  {
    id: "f1",
    name: "㈱西原食品 本社工場",
    address: "鹿児島県鹿児島市本名町1744番地1号",
    companyId: "c1",
    loginId: "530002",
    hasPassword: true,
    closedDays: ["2025-04-05", "2025-04-15", "2025-04-24", "2025-04-26"],
    ledgerSlugs: ["water-inspection"],
  },
  {
    id: "f2",
    name: "㈱西原食品 第二工場",
    address: "鹿児島県鹿児島市本名町1822番地1号",
    companyId: "c1",
    loginId: "530003",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: ["water-inspection", "cleaning-record"],
  },
  {
    id: "f3",
    name: "㈱西原食品 伊佐工場",
    address: "鹿児島県伊佐市菱刈重留1476番",
    companyId: "c1",
    loginId: "530004",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f4",
    name: "㈱ヒコシマリン 本社工場",
    address: "山口県下関市彦島西山町5丁目4番37号",
    companyId: "c2",
    loginId: "530005",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: ["equipment-inspection"],
  },
  {
    id: "f5",
    name: "㈱ヒコシマリン カネハチ静岡工場",
    address: "静岡県榛原郡吉田町川尻3138-32",
    companyId: "c2",
    loginId: "530006",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f6",
    name: "㈱ゆば将 本社工場",
    address: "京都府京都市南区東九条南田町5-1",
    companyId: "c3",
    loginId: "530007",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: ["sensory-inspection"],
  },
  {
    id: "f7",
    name: "㈱匠フーズ 本社工場",
    address: "福岡県糟屋郡粕屋町甲仲原四丁目6番10号",
    companyId: "c4",
    loginId: "530008",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f8",
    name: "㈱薩摩家 本社工場",
    address: "鹿児島県鹿児島市七ツ島1丁目1番7号",
    companyId: "c5",
    loginId: "530009",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: ["scale-inspection"],
  },
  {
    id: "f9",
    name: "㈱西通りプリン 本社工場",
    address: "福岡県糟屋郡志免町別府西一丁目2番3号",
    companyId: "c6",
    loginId: "530010",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f10",
    name: "㈱西通りプリン 安曇野工場",
    address: "長野県安曇野市穂高北穂高2047番地7",
    companyId: "c6",
    loginId: "530011",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f11",
    name: "㈱桜寿食品 本社工場",
    address: "熊本県熊本市西区花園6-22-1",
    companyId: "c7",
    loginId: "530012",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f12",
    name: "㈱亜味撰 本社工場",
    address: "宮崎県宮崎市橘通西3-9-14",
    companyId: "c8",
    loginId: "530013",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f13",
    name: "㈱ゆう屋 本社工場",
    address: "大分県大分市中央町1-2-3",
    companyId: "c9",
    loginId: "530014",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f14",
    name: "㈱五島製麺 本社工場",
    address: "長崎県五島市浜町2-1-12",
    companyId: "c10",
    loginId: "530015",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f15",
    name: "㈱有明農産 本社工場",
    address: "佐賀県佐賀市有明町大字牛津14-6",
    companyId: "c11",
    loginId: "530016",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f16",
    name: "龍屋物産㈱ 本社工場",
    address: "沖縄県那覇市泉崎1-10-8",
    companyId: "c12",
    loginId: "530017",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f17",
    name: "松山製菓㈱ 本社工場",
    address: "愛知県知多市新知台2-4-9",
    companyId: "c13",
    loginId: "530018",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f18",
    name: "松山製菓㈱ 知多かなん堂工場",
    address: "愛知県知多市かなん堂3-1-2",
    companyId: "c13",
    loginId: "530019",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f19",
    name: "はやしハム㈱ 本社工場",
    address: "群馬県高崎市問屋町3-5-2",
    companyId: "c14",
    loginId: "530020",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f20",
    name: "あったか市場㈱ キットファクトリー",
    address: "北海道札幌市中央区北3条西5-1",
    companyId: "c15",
    loginId: "530021",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
  {
    id: "f21",
    name: "㈱鈴木商会 製造部門",
    address: "新潟県新潟市中央区東大通2-4-4",
    companyId: "c16",
    loginId: "530022",
    hasPassword: true,
    closedDays: [],
    ledgerSlugs: [],
  },
];
