import type { ScaleApprovalRecord } from "./types";

export const scaleApprovalRecords: ScaleApprovalRecord[] = [
  {
    id: "sa1",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン①",
    serialNumber: "ABC-123456",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa2",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン②",
    serialNumber: "ABC-123457",
    post: "プリン",
    skipped: false,
    operationCheck: "ng",
    operationCause: "表示が点灯しない",
    operationAction: "修理",
    repairStatus: "action_needed",
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "修理担当者へ連絡済み",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa3",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン③",
    serialNumber: "ABC-123458",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa4",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン④",
    serialNumber: "ABC-123459",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa5",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン⑤",
    serialNumber: "ABC-123460",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 110,
    weightCause: "故障",
    remarks: "表示値のズレを確認、次回点検まで経過観察",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa6",
    requestId: "2",
    date: "2025-04-01",
    scaleLabel: "プリン⑥",
    serialNumber: "ABC-123461",
    post: "プリン",
    skipped: false,
    operationCheck: "ng",
    operationCause: "重量が安定しない",
    operationAction: "電池交換",
    repairStatus: "repairing",
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "電池交換にて対応中",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa7",
    requestId: "3",
    date: "2025-04-01",
    scaleLabel: "アイス①",
    serialNumber: "ABC-423456",
    post: "アイス",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "佐々木亮",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sa8",
    requestId: "3",
    date: "2025-04-01",
    scaleLabel: "アイス②",
    serialNumber: "ABC-423457",
    post: "アイス",
    skipped: true,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "冷凍庫メンテナンス中のため点検見送り",
    implementer: "佐々木亮",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
];
