import type { InspectionRecord } from "./types";

export const inspectionRecords: InspectionRecord[] = [
  {
    id: "r1",
    date: "2025-04-01",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "全項目正常、異常なし",
    implementer: "田中太郎",
    confirmer: "山田花子",
    approvalStatus: "pending",
    metalComments: [
      {
        id: "mc1",
        author: "田中太郎",
        timestamp: "2026.08.19 10:39",
        text: "金属探知機の動作確認を実施しました。全ての検査項目で正常に動作しています。",
      },
      {
        id: "mc2",
        author: "佐藤花子",
        timestamp: "2026.08.23 15:45",
        text: "キャリブレーション値の確認を完了しました。問題ありません。",
      },
    ],
    xrayComments: [
      {
        id: "xc1",
        author: "田中太郎",
        timestamp: "2026.08.19 11:15",
        text: "X線探知機の感度設定を確認しました。正常範囲内です。",
      },
      {
        id: "xc2",
        author: "山田花子",
        timestamp: "2026.08.27 16:20",
        text: "定期メンテナンススケジュールを確認しました。次回は9月中旬の予定です。",
      },
    ],
    sessions: [
      {
        segment: "始業",
        remarks:
          "エコスター タンク部に油汚れを確認。分解洗浄にて対応済み。次回点検時に再確認予定。その他の点検項目は異常なし。",
        points: [
          {
            location: "エコスター",
            items: [
              { name: "定量部", status: "ok", timestamp: "2025/04/01 07:15", inspector: "佐藤健一" },
              {
                name: "タンク部",
                status: "ng",
                cause: "汚れ",
                action: "その他 / 内部に油汚れを確認、分解洗浄を実施済み",
                timestamp: "2025/04/01 07:08",
                inspector: "佐藤健一",
              },
              { name: "駆動ベルト", status: "ok", timestamp: "2025/04/01 06:52", inspector: "佐藤健一" },
            ],
          },
          {
            location: "ボイル槽",
            items: [
              { name: "温度計・水位", status: "ok", timestamp: "2025/04/01 06:52", inspector: "佐藤健一" },
            ],
          },
        ],
      },
      {
        segment: "終業",
        remarks: "点検内容に関する補足を入力できます（任意）",
        points: [
          {
            location: "エコスター",
            items: [
              { name: "定量部", status: "ok", timestamp: "2025/04/01 17:15", inspector: "佐藤健一" },
              {
                name: "タンク部",
                status: "ng",
                cause: "汚れ",
                action: "その他 / 内部に油汚れを確認、分解洗浄を実施済み",
                timestamp: "2025/04/01 17:08",
                inspector: "佐藤健一",
              },
              { name: "駆動ベルト", status: "ok", timestamp: "2025/04/01 16:52", inspector: "佐藤健一" },
            ],
          },
          {
            location: "ボイル槽",
            items: [
              { name: "温度計・水位", status: "ok", timestamp: "2025/04/01 16:45", inspector: "佐藤健一" },
            ],
          },
        ],
      },
    ],
    comment: "点検内容確認しました。見送り箇所については、明日朝一で対応をお願いします。",
  },
  {
    id: "r2",
    date: "2025-04-01",
    lineLabel: "【毎週】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "高橋美咲",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r3",
    date: "2025-04-01",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ng",
    remarks: "タンク内部に油汚れを確認、分解洗浄にて対応済み",
    implementer: "渡辺真由",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r4",
    date: "2025-04-01",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "skip",
    remarks: "点検見送り ライン停止中のため",
    implementer: "小林誠司",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r5",
    date: "2025-04-02",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "山本拓海",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r6",
    date: "2025-04-02",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ok",
    remarks: "ベルト摩耗あり、次回交換予定",
    implementer: "吉田浩二",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r7",
    date: "2025-04-02",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "ok",
    remarks: "異常なし",
    implementer: "田村康平",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r8",
    date: "2025-04-03",
    lineLabel: "【毎日】豆乳ライン",
    resultIcon: "ok",
    remarks: "",
    implementer: "松本奈々",
    confirmer: "加藤由美",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r9",
    date: "2025-04-03",
    lineLabel: "【毎日】ゆばライン（つまみ関係）",
    resultIcon: "ok",
    remarks: "",
    implementer: "佐藤健一",
    confirmer: "伊藤裕太",
    approvalStatus: "pending",
    sessions: [],
  },
  {
    id: "r10",
    date: "2025-04-03",
    lineLabel: "【毎日】ゆばライン（その他）",
    resultIcon: "ok",
    remarks: "パッキン交換済み、動作確認完了",
    implementer: "高橋美咲",
    confirmer: "鈴木雅人",
    approvalStatus: "pending",
    sessions: [],
  },
];
