import type { ScaleRecord } from "./types";

export const scaleRecords: ScaleRecord[] = [
  {
    id: "sc1",
    date: "2025-04-01",
    scaleLabel: "プリン①",
    serialNumber: "ABC-123456",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc2",
    date: "2025-04-01",
    scaleLabel: "プリン②",
    serialNumber: "ABC-123457",
    post: "プリン",
    skipped: false,
    operationCheck: "ng",
    operationCause: "表示が点灯しない",
    operationAction: "修理",
    repairStatus: "action_needed",
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "修理担当者へ連絡済み",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc3",
    date: "2025-04-01",
    scaleLabel: "プリン③",
    serialNumber: "ABC-123458",
    post: "プリン",
    skipped: true,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "ライン停止中のため点検見送り",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc4",
    date: "2025-04-01",
    scaleLabel: "プリン④",
    serialNumber: "ABC-123459",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc5",
    date: "2025-04-01",
    scaleLabel: "プリン⑤",
    serialNumber: "ABC-123460",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 110,
    weightCause: "故障",
    remarks: "表示値のズレを確認、次回点検まで経過観察",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc6",
    date: "2025-04-02",
    scaleLabel: "プリン①",
    serialNumber: "ABC-123456",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "sc7",
    date: "2025-04-02",
    scaleLabel: "プリン②",
    serialNumber: "ABC-123457",
    post: "プリン",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "修理完了後の再点検、異常なし",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "rejected",
  },
  {
    id: "sc8",
    date: "2025-04-01",
    scaleLabel: "アイス①",
    serialNumber: "ABC-423456",
    post: "アイス",
    skipped: false,
    operationCheck: "ok",
    operationCause: "",
    operationAction: null,
    repairStatus: null,
    levelCheck: "ok",
    dirtCheck: "ok",
    referenceWeight: 100,
    displayValue: 100,
    weightCause: null,
    remarks: "",
    implementer: "佐々木亮",
    confirmer: "山本真理",
    approvalStatus: "pending",
  },
  {
    id: "sc9",
    date: "2025-04-01",
    scaleLabel: "アイス②",
    serialNumber: "ABC-423457",
    post: "アイス",
    skipped: false,
    operationCheck: "ng",
    operationCause: "重量が安定しない",
    operationAction: "電池交換",
    repairStatus: "done",
    levelCheck: null,
    dirtCheck: null,
    referenceWeight: 100,
    displayValue: null,
    weightCause: null,
    remarks: "電池交換にて対応完了",
    implementer: "佐々木亮",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
];
