import type { ChemicalRecord } from "./types";

export const chemicalRecords: ChemicalRecord[] = [
  {
    id: "dch1",
    date: "2025-04-01",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "入庫",
    previousStock: "5,000g",
    quantity: "1,000g",
    currentStock: "4,000g",
    storageLocation: "小型物置",
    remarks: "月次定期発注による補充入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
    comments: [
      {
        id: "c1",
        author: "鈴木修",
        timestamp: "2026.08.19 10:39",
        text: "検索条件を確認しました。問題ありません。",
      },
      {
        id: "c2",
        author: "山田花子",
        timestamp: "2026.08.23 15:45",
        text: "データ抽出の期間を再度ご確認ください。",
      },
    ],
  },
  {
    id: "dch2",
    date: "2025-04-01",
    chemicalName: "過酸化水素",
    type: "出庫",
    previousStock: "4,000g",
    quantity: "500g",
    currentStock: "3,500g",
    storageLocation: "冷蔵庫",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch3",
    date: "2025-04-02",
    chemicalName: "アンモニア水",
    type: "入庫",
    previousStock: "3,500g",
    quantity: "2,000g",
    currentStock: "5,500g",
    storageLocation: "倉庫棟A",
    remarks: "緊急発注分の追加入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch4",
    date: "2025-04-03",
    chemicalName: "クエン酸",
    type: "出庫",
    previousStock: "5,500g",
    quantity: "1,000g",
    currentStock: "4,500g",
    storageLocation: "大型物置",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch5",
    date: "2025-04-03",
    chemicalName: "塩酸",
    type: "出庫",
    previousStock: "4,500g",
    quantity: "500g",
    currentStock: "4,000g",
    storageLocation: "化学物質保管室",
    remarks: "洗浄作業使用分として出庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
];
