import type { ChemicalRecord } from "./types";

export const chemicalRecords: ChemicalRecord[] = [
  {
    id: "dch1",
    date: "2025-04-01",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "入庫",
    previousStock: "5,000g",
    quantity: "1,000g",
    currentStock: "4,000g",
    storageLocation: "小型物置",
    remarks: "月次定期発注による補充入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch2",
    date: "2025-04-01",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "出庫",
    previousStock: "4,000g",
    quantity: "500g",
    currentStock: "3,500g",
    storageLocation: "小型物置",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch3",
    date: "2025-04-02",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "入庫",
    previousStock: "3,500g",
    quantity: "2,000g",
    currentStock: "5,500g",
    storageLocation: "小型物置",
    remarks: "緊急発注分の追加入庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch4",
    date: "2025-04-03",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "出庫",
    previousStock: "5,500g",
    quantity: "1,000g",
    currentStock: "4,500g",
    storageLocation: "小型物置",
    remarks: "",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
  {
    id: "dch5",
    date: "2025-04-03",
    chemicalName: "次亜塩素酸ナトリウム",
    type: "出庫",
    previousStock: "4,500g",
    quantity: "500g",
    currentStock: "4,000g",
    storageLocation: "小型物置",
    remarks: "洗浄作業使用分として出庫",
    implementer: "田中裕子",
    confirmer: "山本真理",
    approvalStatus: "approved",
  },
];
