import type { AdditiveRecord } from "./types";

export const additiveRecords: AdditiveRecord[] = [
  {
    id: "add1",
    date: "2025-04-01",
    additiveName: "ソルビン酸カリウム",
    type: "入庫",
    previousStock: "2,000g",
    quantity: "500g",
    currentStock: "1,500g",
    storageLocation: "棚A",
    remarks: "月次定期発注による補充入庫",
    implementer: "佐藤花子",
    confirmer: "鈴木由美",
    approvalStatus: "approved",
  },
  {
    id: "add2",
    date: "2025-04-01",
    additiveName: "ソルビン酸カリウム",
    type: "出庫",
    previousStock: "1,500g",
    quantity: "250g",
    currentStock: "1,250g",
    storageLocation: "棚A",
    remarks: "",
    implementer: "佐藤花子",
    confirmer: "鈴木由美",
    approvalStatus: "approved",
  },
  {
    id: "add3",
    date: "2025-04-02",
    additiveName: "安息香酸ナトリウム",
    type: "入庫",
    previousStock: "3,000g",
    quantity: "1,000g",
    currentStock: "2,000g",
    storageLocation: "棚B",
    remarks: "新規商品用追加注文",
    implementer: "佐藤花子",
    confirmer: "鈴木由美",
    approvalStatus: "approved",
  },
  {
    id: "add4",
    date: "2025-04-03",
    additiveName: "ソルビン酸カリウム",
    type: "出庫",
    previousStock: "1,250g",
    quantity: "500g",
    currentStock: "750g",
    storageLocation: "棚A",
    remarks: "",
    implementer: "佐藤花子",
    confirmer: "鈴木由美",
    approvalStatus: "approved",
  },
  {
    id: "add5",
    date: "2025-04-03",
    additiveName: "安息香酸ナトリウム",
    type: "出庫",
    previousStock: "2,000g",
    quantity: "300g",
    currentStock: "1,700g",
    storageLocation: "棚B",
    remarks: "製造工程用として出庫",
    implementer: "佐藤花子",
    confirmer: "鈴木由美",
    approvalStatus: "approved",
  },
];
