import type { Staff } from "./types";

export const INITIAL_STAFF: Staff[] = [
  {
    id: "st1",
    name: "山田太郎",
    employeeNumber: "0123456",
    systemAuthority: "factory_staff",
    companyId: "c1",
    assignments: [
      { factoryId: "f1", role: "operator" },
      { factoryId: "f2", role: "admin" },
    ],
    email: "yamada@example.com",
    hasPassword: true,
  },
  {
    id: "st2",
    name: "佐藤花子",
    employeeNumber: "0123457",
    systemAuthority: "factory_staff",
    companyId: "c1",
    assignments: [{ factoryId: "f1", role: "checker" }],
    email: "sato@example.com",
    hasPassword: true,
  },
  {
    id: "st3",
    name: "鈴木一郎",
    employeeNumber: "0123458",
    systemAuthority: "hq_admin",
    companyId: "c1",
    assignments: [{ factoryId: "f1", role: "approver" }],
    email: "suzuki@example.com",
    hasPassword: true,
  },
  {
    id: "st4",
    name: "高橋美咲",
    employeeNumber: "0123459",
    systemAuthority: "factory_staff",
    companyId: "c2",
    assignments: [{ factoryId: "f4", role: "operator" }],
    email: "takahashi@example.com",
    hasPassword: true,
  },
  {
    id: "st5",
    name: "田中健太",
    employeeNumber: "0123460",
    systemAuthority: "factory_staff",
    companyId: "c2",
    assignments: [{ factoryId: "f5", role: "operator" }],
    email: "tanaka@example.com",
    hasPassword: true,
  },
  {
    id: "st6",
    name: "伊藤真由",
    employeeNumber: "0123461",
    systemAuthority: "factory_staff",
    companyId: "c3",
    assignments: [{ factoryId: "f6", role: "checker" }],
    email: "ito@example.com",
    hasPassword: true,
  },
  {
    id: "st7",
    name: "渡辺翔",
    employeeNumber: "0123462",
    systemAuthority: "factory_staff",
    companyId: "c4",
    assignments: [{ factoryId: "f7", role: "operator" }],
    email: "watanabe@example.com",
    hasPassword: true,
  },
  {
    id: "st8",
    name: "中村悠人",
    employeeNumber: "0123463",
    systemAuthority: "factory_staff",
    companyId: "c5",
    assignments: [{ factoryId: "f8", role: "operator" }],
    email: "nakamura@example.com",
    hasPassword: true,
  },
];
