import type { MachineSearchRecord } from "./types";

export const machineSearchRecords: MachineSearchRecord[] = [
  {
    id: "dm1",
    machineName: "金探1号機（500g以下の場合）",
    date: "2025-04-01",
    metalDetectorModel: "GM-500S",
    xrayDetectorModel: "XR-500S",
    weightCheckerModel: "WC-500S",
    result: "OK",
    confirmer: "山田太郎",
    approvalStatus: "pending",
    records: [
      {
        id: "dm1-1",
        category: "開始",
        time: "08:00",
        content: "動作確認",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm1-2",
        category: "開始",
        time: "08:05",
        content: "テストピース",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm1-3",
        category: "開始",
        time: "08:10",
        content: "製品通過",
        passedProduct: "仕出しだし巻き玉子 冷凍",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm1-4",
        category: "終了",
        time: "17:00",
        content: "製品通過",
        passedProduct: "仕出しだし巻き玉子 冷凍",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm1-5",
        category: "終了",
        time: "17:05",
        content: "テストピース",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm1-6",
        category: "終了",
        time: "17:10",
        content: "異常反応",
        passedProduct: "ー",
        result: "NG",
        remarks: "",
        inspectorName: "田中太郎",
      },
    ],
  },
  {
    id: "dm2",
    machineName: "金探1号機（1kg以下の場合）",
    date: "2025-04-01",
    metalDetectorModel: "GM-1000S",
    xrayDetectorModel: "XR-1000S",
    weightCheckerModel: "WC-1000S",
    result: "NG",
    confirmer: "佐藤花子",
    approvalStatus: "rejected",
    records: [
      {
        id: "dm2-1",
        category: "開始",
        time: "08:00",
        content: "動作確認",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "実施者02",
      },
      {
        id: "dm2-2",
        category: "ー",
        time: "12:30",
        content: "異常反応",
        passedProduct: "茶碗蒸しの素（濃縮）",
        result: "NG",
        remarks: "金属異物を検知したため製品を廃棄",
        inspectorName: "実施者02",
      },
    ],
  },
  {
    id: "dm3",
    machineName: "金探1号機（500g以下の場合）",
    date: "2025-04-02",
    metalDetectorModel: "GM-500S",
    xrayDetectorModel: "XR-500S",
    weightCheckerModel: "WC-500S",
    result: "OK",
    confirmer: "山田太郎",
    approvalStatus: "approved",
    records: [
      {
        id: "dm3-1",
        category: "開始",
        time: "08:00",
        content: "動作確認",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
      {
        id: "dm3-2",
        category: "終了",
        time: "17:00",
        content: "動作確認",
        passedProduct: "ー",
        result: "OK",
        remarks: "",
        inspectorName: "田中太郎",
      },
    ],
  },
];
