import type { MetalDetectorUnit } from "./types";

export { CANDIDATE_PRODUCTS } from "../metal-xray-detection/mockData";

export const METAL_DETECTOR_UNITS: MetalDetectorUnit[] = [
  {
    id: "u1",
    name: "金属探知機1号機",
    factoryName: "㈱西原食品 本社工場",
    checklistName: "製造ラインXXXXXXX",
    appDisplayFrom: "2025/04/01",
    appDisplayTo: "2028/04/01",
    metalDetector: "記録する",
    metalDetectorNo: "XXXXXXX",
    xrayDetector: "記録する",
    xrayDetectorNo: "XXXXXXX",
    weightChecker: "記録する",
    weightCheckerNo: "XXXXXXX",
    sealing: "記録する",
    mainProducts: ["製品名XXXXXXXXX", "製品名YYYYYYYYY", "製品名ZZZZZZZZZ"],
    settings: [
      {
        id: "s1",
        productName: "仕出しだし巻き玉子 冷凍",
        settingNumber: "標準",
        fe: "1.5",
        sus: "2.0",
      },
      {
        id: "s4",
        productName: "マンゴープリン ストレート 1kg",
        settingNumber: "1",
        fe: "1.2",
        sus: "1.8",
      },
      {
        id: "s5",
        productName: "抹茶アイス 業務用",
        settingNumber: "2",
        fe: "1.0",
        sus: "1.5",
      },
      {
        id: "s6",
        productName: "ティラミスケーキ 冷凍",
        settingNumber: "標準",
        fe: "1.3",
        sus: "1.9",
      },
    ],
  },
  {
    id: "u2",
    name: "金属探知機2号機",
    factoryName: "㈱西原食品 本社工場",
    checklistName: "製造ラインYYYYYYYY",
    appDisplayFrom: "2025/04/01",
    appDisplayTo: "2028/04/01",
    metalDetector: "記録する",
    metalDetectorNo: "YYYYYYY",
    xrayDetector: "記録しない",
    xrayDetectorNo: "",
    weightChecker: "記録する",
    weightCheckerNo: "YYYYYYY",
    sealing: "記録しない",
    mainProducts: ["製品名AAAAAAAA"],
    settings: [],
  },
  {
    id: "u3",
    name: "金属探知機3号機",
    factoryName: "㈱西原食品 本社工場",
    checklistName: "製造ラインZZZZZZZZ",
    appDisplayFrom: "2025/04/01",
    appDisplayTo: "2028/04/01",
    metalDetector: "記録する",
    metalDetectorNo: "ZZZZZZZ",
    xrayDetector: "記録する",
    xrayDetectorNo: "ZZZZZZZ",
    weightChecker: "記録しない",
    weightCheckerNo: "",
    sealing: "記録する",
    mainProducts: ["製品名BBBBBBBB", "製品名CCCCCCCC"],
    settings: [
      {
        id: "s2",
        productName: "茶碗蒸しの素（濃縮）",
        settingNumber: "1",
        fe: "1.2",
        sus: "1.8",
      },
      {
        id: "s3",
        productName: "ふわとろスクランブルエッグ",
        settingNumber: "2",
        fe: "1.0",
        sus: "0",
      },
    ],
  },
];
