import type { LogEntry } from "./types";

export const LOG_ENTRIES: LogEntry[] = [
  {
    id: "l1",
    timestamp: "2025-04-01 08:12:03",
    screenType: "app",
    factoryId: "f1",
    staffName: "田中太郎",
    role: "実施者",
    ledgerSlug: "water-inspection",
    action: "使用水の点検を記録",
  },
  {
    id: "l2",
    timestamp: "2025-04-01 09:30:45",
    screenType: "app",
    factoryId: "f1",
    staffName: "佐藤花子",
    role: "確認者",
    ledgerSlug: "water-inspection",
    action: "使用水の点検を確認",
  },
  {
    id: "l3",
    timestamp: "2025-04-01 10:05:12",
    screenType: "admin",
    factoryId: "f1",
    staffName: "鈴木一郎",
    role: "承認者",
    ledgerSlug: "water-inspection",
    action: "使用水の点検を承認",
  },
  {
    id: "l4",
    timestamp: "2025-04-01 11:20:00",
    screenType: "app",
    factoryId: "f2",
    staffName: "山田太郎",
    role: "実施者",
    ledgerSlug: "cleaning-record",
    action: "清掃記録を記録",
  },
  {
    id: "l5",
    timestamp: "2025-04-01 13:40:22",
    screenType: "app",
    factoryId: "f4",
    staffName: "高橋美咲",
    role: "実施者",
    ledgerSlug: "equipment-inspection",
    action: "機械器具点検を記録",
  },
  {
    id: "l6",
    timestamp: "2025-04-01 14:15:38",
    screenType: "admin",
    factoryId: "f1",
    staffName: "管理者01",
    role: "管理者",
    ledgerSlug: "additive-management",
    action: "添加物情報を新規登録",
  },
  {
    id: "l7",
    timestamp: "2025-04-02 08:02:51",
    screenType: "app",
    factoryId: "f5",
    staffName: "田中健太",
    role: "実施者",
    ledgerSlug: "equipment-inspection",
    action: "機械器具点検を記録",
  },
  {
    id: "l8",
    timestamp: "2025-04-02 09:18:07",
    screenType: "app",
    factoryId: "f6",
    staffName: "伊藤真由",
    role: "確認者",
    ledgerSlug: "sensory-inspection",
    action: "官能検査記録を確認",
  },
  {
    id: "l9",
    timestamp: "2025-04-02 10:44:29",
    screenType: "admin",
    factoryId: "f1",
    staffName: "管理者01",
    role: "管理者",
    ledgerSlug: "water-inspection",
    action: "点検場所情報を更新",
  },
  {
    id: "l10",
    timestamp: "2025-04-02 11:55:14",
    screenType: "app",
    factoryId: "f7",
    staffName: "渡辺翔",
    role: "実施者",
    ledgerSlug: "scale-inspection",
    action: "秤点検記録を記録",
  },
  {
    id: "l11",
    timestamp: "2025-04-02 13:07:52",
    screenType: "app",
    factoryId: "f8",
    staffName: "中村悠人",
    role: "実施者",
    ledgerSlug: "metal-xray-detection",
    action: "金属探知機・X線探知機の記録を記録",
  },
  {
    id: "l12",
    timestamp: "2025-04-02 15:33:19",
    screenType: "admin",
    factoryId: "f1",
    staffName: "管理者01",
    role: "管理者",
    action: "工場情報を更新",
  },
  {
    id: "l13",
    timestamp: "2025-04-03 08:20:44",
    screenType: "app",
    factoryId: "f1",
    staffName: "田中太郎",
    role: "実施者",
    ledgerSlug: "water-inspection",
    action: "使用水の点検を記録",
  },
  {
    id: "l14",
    timestamp: "2025-04-03 09:41:03",
    screenType: "app",
    factoryId: "f2",
    staffName: "山田太郎",
    role: "管理者",
    ledgerSlug: "cleaning-record",
    action: "清掃記録を削除",
  },
  {
    id: "l15",
    timestamp: "2025-04-03 10:12:37",
    screenType: "admin",
    factoryId: "f2",
    staffName: "管理者01",
    role: "管理者",
    action: "企業情報を新規登録",
  },
  {
    id: "l16",
    timestamp: "2025-04-03 11:50:26",
    screenType: "app",
    factoryId: "f4",
    staffName: "高橋美咲",
    role: "確認者",
    ledgerSlug: "equipment-inspection",
    action: "機械器具点検を確認",
  },
  {
    id: "l17",
    timestamp: "2025-04-03 13:05:58",
    screenType: "admin",
    factoryId: "f1",
    staffName: "管理者01",
    role: "管理者",
    action: "職員情報を新規登録",
  },
  {
    id: "l18",
    timestamp: "2025-04-03 14:28:41",
    screenType: "app",
    factoryId: "f6",
    staffName: "伊藤真由",
    role: "実施者",
    ledgerSlug: "sample-management",
    action: "検体の管理を記録",
  },
  {
    id: "l19",
    timestamp: "2025-04-04 08:09:16",
    screenType: "app",
    factoryId: "f7",
    staffName: "渡辺翔",
    role: "承認者",
    ledgerSlug: "scale-inspection",
    action: "秤点検記録を承認",
  },
  {
    id: "l20",
    timestamp: "2025-04-04 09:22:53",
    screenType: "admin",
    factoryId: "f3",
    staffName: "管理者01",
    role: "管理者",
    action: "工場情報を新規登録",
  },
  {
    id: "l21",
    timestamp: "2025-04-04 10:47:05",
    screenType: "app",
    factoryId: "f8",
    staffName: "中村悠人",
    role: "確認者",
    ledgerSlug: "metal-xray-detection",
    action: "金属探知機・X線探知機の記録を確認",
  },
  {
    id: "l22",
    timestamp: "2025-04-04 13:15:39",
    screenType: "app",
    factoryId: "f1",
    staffName: "鈴木一郎",
    role: "承認者",
    ledgerSlug: "chemical-management",
    action: "薬品管理を承認",
  },
  {
    id: "l23",
    timestamp: "2025-04-04 15:02:12",
    screenType: "admin",
    factoryId: "f1",
    staffName: "管理者01",
    role: "管理者",
    action: "保管場所を新規登録",
  },
  {
    id: "l24",
    timestamp: "2025-04-05 08:33:47",
    screenType: "app",
    factoryId: "f2",
    staffName: "山田太郎",
    role: "実施者",
    ledgerSlug: "glass-plastic",
    action: "ガラス・プラスチック管理を記録",
  },
  {
    id: "l25",
    timestamp: "2025-04-05 09:56:24",
    screenType: "app",
    factoryId: "f1",
    staffName: "佐藤花子",
    role: "確認者",
    ledgerSlug: "water-inspection",
    action: "使用水の点検を確認",
  },
];
