import type { SampleRecord } from "./types";

export const sampleRecords: SampleRecord[] = [
  {
    id: "ds1",
    date: "2025-04-01",
    productName: "仕出しだし巻き玉子 冷凍",
    expirationDate: "2026-06-30",
    manufactureDate: "2025-07-01",
    sampleType: "小分け",
    sampleQuantity: "100",
    unit: "g",
    storageLocation: "第一冷蔵庫",
    remarks: "月次定期保存分",
    status: "保管中",
    implementer: "田中太郎",
    confirmer: "確認者01",
    approvalStatus: "approved",
  },
  {
    id: "ds2",
    date: "2025-04-02",
    productName: "鮭の西京焼き 惣菜",
    expirationDate: "2026-07-15",
    manufactureDate: "2025-07-02",
    sampleType: "原本",
    sampleQuantity: "1",
    unit: "P",
    storageLocation: "第二冷蔵庫",
    remarks: "",
    status: "保管中",
    implementer: "実施者02",
    confirmer: "確認者01",
    approvalStatus: "pending",
  },
  {
    id: "ds3",
    date: "2025-04-03",
    productName: "野菜の煮物パック",
    expirationDate: "2025-05-01",
    manufactureDate: "2025-04-03",
    sampleType: "小分け",
    sampleQuantity: "50",
    unit: "g",
    storageLocation: "第一冷蔵庫",
    remarks: "賞味期限切れのため破棄",
    status: "破棄済み",
    discardedDate: "2025-05-02",
    discardReason: "賞味期限切れ",
    implementer: "田中太郎",
    confirmer: "確認者02",
    approvalStatus: "approved",
  },
  {
    id: "ds4",
    date: "2025-04-04",
    productName: "唐揚げ 冷凍",
    expirationDate: "2026-08-01",
    manufactureDate: "2025-08-01",
    sampleType: "原本",
    sampleQuantity: "1",
    unit: "P",
    storageLocation: "冷凍庫A",
    remarks: "不具合調査のため使用。",
    status: "破棄済み",
    discardedDate: "2025-04-20",
    discardReason: "その他",
    discardReasonNote: "不具合調査のため使用。",
    implementer: "実施者03",
    confirmer: "確認者02",
    approvalStatus: "rejected",
  },
  {
    id: "ds5",
    date: "2025-04-05",
    productName: "ポテトサラダ 業務用",
    expirationDate: "2025-05-10",
    manufactureDate: "2025-04-05",
    sampleType: "小分け",
    sampleQuantity: "200",
    unit: "g",
    storageLocation: "第二冷蔵庫",
    remarks: "",
    status: "保管中",
    implementer: "実施者02",
    confirmer: "確認者01",
    approvalStatus: "approved",
  },
];
