import type { SampleApprovalRecord } from "./types";

export const sampleApprovalRecords: SampleApprovalRecord[] = [
  {
    id: "sa1",
    date: "2025-07-01",
    productName: "仕出しだし巻き玉子 冷凍",
    expirationDate: "2026-06-30",
    manufactureDate: "2025-07-01",
    sampleType: "製品",
    sampleQuantity: "1",
    unit: "P",
    storageLocation: "第一冷蔵庫",
    remarks: "月次定期保存分",
    status: "保管中",
    implementer: "田中太郎",
    confirmer: "鈴木一郎",
    approvalStatus: "pending",
    timestamp: "田中太郎 2025/07/01 10:30",
  },
  {
    id: "sa2",
    date: "2025-04-02",
    productName: "仕出しだし巻き玉子 冷凍",
    expirationDate: "2026-06-30",
    manufactureDate: "2025-07-02",
    sampleType: "原本",
    sampleQuantity: "1",
    unit: "P",
    storageLocation: "第一冷蔵庫",
    remarks: "",
    status: "保管中",
    implementer: "田中太郎",
    confirmer: "山田太郎",
    approvalStatus: "pending",
    timestamp: "田中太郎 2025/04/02 14:15",
  },
  {
    id: "sa3",
    date: "2025-04-03",
    productName: "仕出しだし巻き玉子 冷凍",
    expirationDate: "2025-05-01",
    manufactureDate: "2025-04-03",
    sampleType: "小分け",
    sampleQuantity: "50",
    unit: "g",
    storageLocation: "第一冷蔵庫",
    remarks: "賞味期限切れのため破棄",
    status: "破棄済み",
    discardedDate: "2025-05-02",
    discardReason: "賞味期限切れ",
    implementer: "田中太郎",
    confirmer: "佐藤花子",
    approvalStatus: "pending",
    timestamp: "田中太郎 2025/04/03 09:45",
  },
  {
    id: "sa4",
    date: "2025-04-04",
    productName: "仕出しだし巻き玉子 冷凍",
    expirationDate: "2026-08-01",
    manufactureDate: "2025-08-01",
    sampleType: "原本",
    sampleQuantity: "1",
    unit: "P",
    storageLocation: "第一冷蔵庫",
    remarks: "不具合調査のため使用。",
    status: "破棄済み",
    discardedDate: "2025-04-20",
    discardReason: "その他",
    discardReasonNote: "不具合調査のため使用。",
    implementer: "佐藤美咲",
    confirmer: "鈴木一郎",
    approvalStatus: "pending",
    timestamp: "佐藤美咲 2025/04/04 11:20",
  },
];
